tokens:
  - mint: So11111111111111111111111111111111111111112
    name: Solana
    ticker: SOL
    description: "Solana is a high-performance blockchain platform known for its ultra-fast transactions, low fees, and powerful smart contract capabilities."
    image: https://upload.wikimedia.org/wikipedia/en/b/b9/Solana_logo.png
    twitter: https://twitter.com/solana
    homepage: https://solana.com
    decimals: 9

  - mint: oooooogrpQeWAF9FYbv7DaKqVGsiALgAXG5K3JwMaLf
    name: ORE
    ticker: ORE
    description: "Liquid digital gold."
    image: https://ore.supply/assets/icon.png
    twitter: https://twitter.com/OREsupply
    homepage: https://ore.supply
    decimals: 11
